/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sudokuvariantsgui;

/**
 *
 * @author chf6534
 */
public class SelectVariant extends javax.swing.JPanel {

    /**
     * Creates new form selectVariant
     */
    public SelectVariant() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        classic = new javax.swing.JButton();
        mega = new javax.swing.JButton();
        mini = new javax.swing.JButton();
        goBack = new javax.swing.JButton();
        menuText = new javax.swing.JLabel();

        classic.setText("Classic");

        mega.setText("Mega");

        mini.setText("Mini");

        goBack.setText("Go Back");

        menuText.setFont(new java.awt.Font("Comic Sans MS", 0, 12)); // NOI18N
        menuText.setText("Select Variant");
        menuText.setToolTipText("");
        menuText.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(menuText))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(classic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(mega)
                            .addComponent(mini)
                            .addComponent(goBack))))
                .addGap(86, 86, 86))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(menuText)
                .addGap(31, 31, 31)
                .addComponent(classic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(36, 36, 36)
                .addComponent(mega)
                .addGap(26, 26, 26)
                .addComponent(mini)
                .addGap(26, 26, 26)
                .addComponent(goBack)
                .addGap(28, 28, 28))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton classic;
    private javax.swing.JButton goBack;
    private javax.swing.JButton mega;
    private javax.swing.JLabel menuText;
    private javax.swing.JButton mini;
    // End of variables declaration//GEN-END:variables
}
